### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by rtpHarry** [chargebee/chargebee-dotnet#14]
Does this support .dotnet core?

**Comment by wullinkm** [comment]
@rtpHarry seems that currently it doesn't I forked it and pushed a version to nuget.org
https://github.com/dexgrid/chargebee-dotnet

In case you might still need it... :)

**Comment by etiennemtl** [comment]
Any updates as to when the library will support net core? @wullinkm your fork currently has some issue with the method `ApiUtil.BuildUrl()` as it uses `WebUtility.UrlEncode(path)` therefore it encodes spaces to + instead of %20. And so the chargebee API returns 404 when retrieving users cards with a customer Id containing a space.

**Comment by winklerp** [comment]
We would also need .net core (.netstandard) support. Any timeline, when this will be available?

**Comment by neilortoo** [comment]
+1 for .dotnet core support.  Is anyone from Chargebee actually tracking this repo?

**Comment by balachargebee** [comment]
Hi there!

We're working on support for .net core. 
ETA- Late February
I'll update the thread once the feature is launched.

Thanks,
Bala Adhethan
Chargebee

**Comment by nils2612** [comment]
Hi @balachargebee, is there an update on this?

**Comment by balachargebee** [comment]
Hey @nils2612 

My apologies, our developers are working on other priority features that had to be taken up. 

We still do have .Net core support in our roadmap and I'll update the new ETA after discussing internally. 

Thank you for your patience.

**Comment by HerrNiklasRaab** [comment]
Also important for us!

**Comment by winklerp** [comment]
Any update on this? This dependency is the only one holding us back from switching to .net core runtime. Please provide .net core support as soon as possible.

thanks!

**Comment by asultan001** [comment]
Any updates on this? It would be great if you had support for .net core.

**Comment by nils2612** [comment]
Hey guys, i am using this package, works fine: https://www.nuget.org/packages/chargebee-core/

**Comment by SangeethaBaskaran** [comment]
Hello @winklerp, @asultan001 , @nils2612 ,

Thanks for being patient with us.

Our developers are actively working on to support .net core now. We need a few more days to discuss this issue in order to get this done as soon as possible. 

Please bear with us. We will get back to you with an update once this is done.

**Comment by brainchest** [comment]
Hi, have you been able to make any progress on this?

**Comment by cb-goutham** [comment]
please use our latest library version - 2.6.8 for .net core support .
